name: Build and Push Docker Image

on:
  push:
    branches:
      - lambda_docker_deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry: 550513526501.dkr.ecr.us-east-2.amazonaws.com

    - name: Build and push Docker image
      run: |
        docker build -t my-lambda-image .
        docker tag my-lambda-image:latest 550513526501.dkr.ecr.us-east-2.amazonaws.com/lambda_docker_deploy:latest
        docker push 550513526501.dkr.ecr.us-east-2.amazonaws.com/lambda_docker_deploy:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-2
