name: Build and Push Docker Image

on:
  push:
    branches:
      - lambda_docker_deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::550513526501:role/ec2_ssm_agent_arpit  # Replace with your IAM role ARN
        aws-region: us-east-2  # Replace with your AWS region

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registries: 550513526501.dkr.ecr.us-east-2.amazonaws.com  # Changed from 'registry' to 'registries'

    - name: Build and push Docker image
      env:
        AWS_REGION: us-east-2  # (ohio)
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        docker build -t my-lambda-image .
        docker tag my-lambda-image:latest 550513526501.dkr.ecr.us-east-2.amazonaws.com/lambda_docker_deploy:latest
        docker push 550513526501.dkr.ecr.us-east-2.amazonaws.com/lambda_docker_deploy:latest
